- name: Get public IP information using ip-api.com
      ansible.builtin.uri:
        url: "http://ip-api.com/json"
        return_content: yes
      register: ip_api_response
    - name: Print the public IP information
      ansible.builtin.debug:
        var: ip_api_response.json
- name: Get public IP information using ip-api.com
       delegate_to: localhost
      ansible.builtin.uri:
        url: "http://ip-api.com/json"
        return_content: yes
      register: ip_api_response
    - name: Print the public IP information
       delegate_to: localhost
      ansible.builtin.debug:
        var: ip_api_response.json
